language: node_js
node_js:
  - "4"
  - "6"
  - "node"

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.8.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - export PATH=./mongodb-linux-x86_64-3.2.8/bin:$PATH
  - mongod --fork --dbpath /tmp/data --syslog
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
